const projects = [
  {
    id: 'project1',
    title: 'Xbox & Microsoft Code Checker',
    img: '/script.webp',
    overlayImg: '/projects/codevault_logs.png',
    link: '/projects/project1',
    date: '2025',
    company: 'Code Vault & Security',
    liveLink: undefined,
    primary: '#090d16',
    accentColor: '#00ff66',
    secondary: '#ffffff',
    fillColor: '#00ff66',
    menuColor: '#00ff66',
    menuFontColor: '#000000',
    fluidColor: '#00ff66',
    images: [
      {
        src: '/projects/codevault_logs.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/script_making.png',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'High-speed automated Xbox & Microsoft code checking and live log vault system.',
      'Supports automated validation, filter by status (Valid/Invalid/Used), rate-limit protection, and real-time live log export.',
    ],
  },
  {
    id: 'project2',
    title: 'Custom Bots & Server Setup',
    img: '/discord.webp',
    overlayImg: '/projects/mcfabazaar_bot.png',
    link: '/projects/project2',
    date: '2025',
    company: 'Automation & Community (McFaBaZaaR / NOXSTORE)',
    liveLink: 'https://discord.gg/mcfabazaar',
    primary: '#0c1021',
    accentColor: '#5865F2',
    secondary: '#ffffff',
    fillColor: '#5865F2',
    menuColor: '#5865F2',
    menuFontColor: '#ffffff',
    fluidColor: '#5865F2',
    images: [
      {
        src: '/projects/mcfabazaar_bot.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/discord_bot.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/discord_setup.jpg',
        tag: 'medium',
        isRight: true,
      },
    ],
    desc: [
      'MCFABAZAAR ULTIMATE BOT – Multi-purpose Discord bot built for store management & support automation.',
      'Includes Ticket System (dropdown categories, staff claim/close, auto-reminders), Payout & Account Delivery (hashed stock tracking to prevent duplicates), Vouch System with auto-blacklist after 3 unpaid vouches, UPI Payments with Tesseract OCR verification, AI Support (GPT-3.5/Llama multi-language), Staff Stats & Leave Management, Stock Drops, and MongoDB integration.',
    ],
  },
  {
    id: 'project3',
    title: 'Windows Optimization & Script Automation',
    img: '/optimization.webp',
    overlayImg: '/overlay1.png',
    link: '/projects/project3',
    date: '2025',
    company: 'Windows Optimization & Scripting',
    liveLink: undefined,
    primary: '#0e1726',
    accentColor: '#00f2ff',
    secondary: '#ffffff',
    fillColor: '#00f2ff',
    menuColor: '#00f2ff',
    menuFontColor: '#000000',
    fluidColor: '#00f2ff',
    images: [
      {
        src: '/overlay1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/windows_opt.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/projects/script_making.png',
        tag: 'medium',
        isRight: true,
      },
    ],
    desc: [
      'Comprehensive Windows OS tuning for peak gaming performance, ultra-low input latency, debloated services, and registry optimization.',
      'Plus custom automated scripts and tools in Python, C++, and C# engineered for workflow efficiency and speed.',
    ],
  },
  {
    id: 'project4',
    title: '3D Website Development (Headshot Paintball)',
    img: '/3d.webp',
    overlayImg: '/projects/headshot_paintball.png',
    link: 'https://headshotpaintball.vercel.app/',
    externalUrl: 'https://headshotpaintball.vercel.app/',
    date: '2025',
    company: 'Headshot Paintball Arena',
    liveLink: 'https://headshotpaintball.vercel.app/',
    primary: '#090d16',
    accentColor: '#00f2ff',
    secondary: '#ffffff',
    fillColor: '#00f2ff',
    menuColor: '#00f2ff',
    menuFontColor: '#000000',
    fluidColor: '#00f2ff',
    images: [
      {
        src: '/projects/headshot_paintball.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/projects/web_dev.png',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'The most adrenaline-fueled arena in Kashmir. Custom engineered 3D responsive website featuring rich interactive visuals, arena showcase, and booking flows.',
      'Visit Live Website: https://headshotpaintball.vercel.app/',
    ],
  },
];

export default projects;
